import Head from 'next/head'
import Image from 'next/image'
import { useContext } from 'react'
import styles from '../../styles/Home.module.css'
import { Contexto } from '../context/context'

export default function Home() {
  const { state } = useContext(Contexto)
  console.log(state)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
    </div>
  )
}
